### ISSUE TITLE
How to deploy to Vercel

### ISSUE THREAD

**Issue by fvision8** [cool-dev-guy/vidsrc.ts#1]
Hi, thanks for moving the project to a new repo.
the previous repo was meant to be deployed on Vercel.
Wondering if this can also be deployed to vercel. Tried with no luck.

Thanks for your effort

**Comment by cool-dev-guy** [comment]
> Hi, thanks for moving the project to a new repo. the previous repo was meant to be deployed on Vercel. Wondering if this can also be deployed to vercel. Tried with no luck.
> 
> Thanks for your effort

Hey @fvision8 added vercel support : https://github.com/cool-dev-guy/vidsrc.ts/tree/vercel
